# lock down access from the TURN server only to kms
---
{{- if eq .Values.mediaServer.deployment.enablement "enable"}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{ .Values.mediaServer.deployment.name}}-network-policy"
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: {{- include "kurento_webrtc_demo.name" .}}
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: {{- include "kurento_webrtc_demo.applicationServer.selectorLabels" .}}
    ports:
    - protocol: UDP
      port: 10000
      endPort: 20000
{{- end}}
---