# Default values for stunner_helm.

stunner:
  namespace: default
  deployment:
    name: stunner
    label: stunner
    replica: 1
    container:
      name: stunnerd
      image:
        repository: ""
        name: l7mp/stunnerd
        pullPolicy: Always
        tag: latest
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
 
      netdebug: enable
  config:
  #PLEASE CUSTOMIZE THE VALUES BELOW 
    STUNNER_REALM: "stunner.l7mp.io"
    STUNNER_PORT: "3478"
    STUNNER_USERNAME: "user"
    STUNNER_PASSWORD: "pass"
    STUNNER_LOGLEVEL: "all:WARN"
    STUNNER_MIN_PORT: "10000"
    STUNNER_MAX_PORT: "20000"

  service:
    port: 3478
  
  networkPolicy: enable

# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80
#   # targetMemoryUtilizationPercentage: 80