apiVersion: v1
kind: ConfigMap
metadata:
  name: prosody-common
  labels:
    app.kubernetes.io/name: jitsi-meet
    app.kubernetes.io/instance: jitsi
data:
  ENABLE_AUTH: "0"
  ENABLE_GUESTS: "1"
  ENABLE_P2P: "0"
  PUBLIC_URL: "https://34.118.96.93.sslip.io" # TODO: Change this
  TURN_ENABLE: "true"
  TURN_HOST: "34.118.91.247"
  TURN_PORT: "3478"
  TURN_CREDENTIALS: "my-shared-secret"
  TURN_TRANSPORT: "tcp"
  JICOFO_AUTH_USER: "focus"
  XMPP_DOMAIN: 34.118.96.93.sslip.io
  XMPP_MUC_DOMAIN: muc.34.118.96.93.sslip.io
  XMPP_AUTH_DOMAIN: auth.34.118.96.93.sslip.io
  XMPP_GUEST_DOMAIN: guest.34.118.96.93.sslip.io
  XMPP_RECORDER_DOMAIN: recorder.34.118.96.93.sslip.io
  XMPP_INTERNAL_MUC_DOMAIN: internal-muc.34.118.96.93.sslip.io
  ENABLE_XMPP_WEBSOCKET: "1"
  ENABLE_COLIBRI_WEBSOCKET: "1"
  XMPP_MUC_MODULES: "external_services,stanzadebug"
  TZ: 'UTC'
  LOG_LEVEL: 'debug'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jitsi-meet
  labels:
    app.kubernetes.io/name: jitsi-meet
    app.kubernetes.io/instance: jitsi
    app.kubernetes.io/component: web
data:
  DISABLE_HTTPS: "1"
  # ENABLE_HTTP_REDIRECT: "0"
  JICOFO_AUTH_USER: 'focus'
  XMPP_BOSH_URL_BASE: 'http://jitsi-prosody.default.svc.cluster.local:5280'
  NGINX_RESOLVER: '10.2.128.10'
  DEPLOYMENTINFO_ENVIRONMENT: "34.118.12.231.sslip.io"
  DEPLOYMENTINFO_REGION: 'Europe/Budapest'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jitsi-jvb
  labels:
    app.kubernetes.io/name: jitsi-meet
    app.kubernetes.io/instance: jitsi
    app.kubernetes.io/component: jvb
data:
  JVB_BREWERY_MUC: 'jvbbrewery'
  JVB_PORT: '10000'
  # JVB_STUN_SERVERS: 'meet-jit-si-turnrelay.jitsi.net:443'
  # JVB_STUN_SERVERS: ' '
  JVB_TCP_HARVESTER_DISABLED: '1'
  XMPP_SERVER: 'jitsi-prosody.default.svc.cluster.local'
  COLIBRI_REST_ENABLED: 'true'
  ENABLE_COLIBRI_WEBSOCKET: 'false'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jitsi-jicofo
  labels:
    app.kubernetes.io/name: jitsi-meet
    app.kubernetes.io/instance: jitsi
    app.kubernetes.io/component: jicofo
data:
  JVB_BREWERY_MUC: 'jvbbrewery'
  XMPP_SERVER: 'jitsi-prosody.default.svc.cluster.local'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jitsi-prosody
  labels:
    app.kubernetes.io/name: prosody
    app.kubernetes.io/instance: jitsi
data: