apiVersion: apps/v1
kind: Deployment
metadata:
  name: jitsi-jicofo
  labels:
    app.kubernetes.io/name: jitsi-meet
    app.kubernetes.io/instance: jitsi
    app.kubernetes.io/component: jicofo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jitsi-meet
      app.kubernetes.io/instance: jitsi
      app.kubernetes.io/component: jicofo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jitsi-meet
        app.kubernetes.io/instance: jitsi
        app.kubernetes.io/component: jicofo
    spec:
      containers:
        - name: jitsi-meet
          image: "jitsi/jicofo:stable-7830"
          imagePullPolicy: IfNotPresent
          envFrom:
          - secretRef:
              name: prosody-jicofo
          - configMapRef:
              name: prosody-common
          - configMapRef:
              name: jitsi-jicofo
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8888
          readinessProbe:
            tcpSocket:
              port: 8888