apiVersion: apps/v1
kind: Deployment
metadata:
  name: jitsi-jvb
  labels:
    app.kubernetes.io/name: jitsi-meet
    app.kubernetes.io/instance: jitsi
    app.kubernetes.io/component: jvb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jitsi-meet
      app.kubernetes.io/instance: jitsi
      app.kubernetes.io/component: jvb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jitsi-meet
        app.kubernetes.io/instance: jitsi
        app.kubernetes.io/component: jvb
    spec:
      containers:
        # - name: net-debug
        #   image: l7mp/net-debug
        - name: jitsi-meet
          image: "jitsi/jvb:stable-7830"
          imagePullPolicy: IfNotPresent
          envFrom:
          - secretRef:
              name: prosody-jvb
          - configMapRef:
              name: prosody-common
          - configMapRef:
              name: jitsi-jvb
          env:
          ports:
            - name: rtp-udp
              containerPort: 10000
              protocol: UDP
          livenessProbe:
            httpGet:
              path: /about/health
              port: 8080
          readinessProbe:
            httpGet:
              path: /about/health
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jitsi-jvb
  labels:
    app.kubernetes.io/name: jitsi-meet
    app.kubernetes.io/instance: jitsi
    app.kubernetes.io/component: jvb
spec:
  # type: ClusterIP
  type: LoadBalancer
  ports:
    - port: 10000
      protocol: UDP
      name: rtp-udp
      targetPort: 10000
  selector:
    app.kubernetes.io/name: jitsi-meet
    app.kubernetes.io/instance: jitsi
    app.kubernetes.io/component: jvb