name: "release"

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.0'

jobs:
  push_to_registry:
    name: Push docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:11})
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag l7mp/stunnerd:${{steps.vars.outputs.tag}}
      - name: Push the tagged Docker image
        run: docker push l7mp/stunnerd:${{steps.vars.outputs.tag}}
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag l7mp/stunnerd:latest
      - name: Push the latest Docker image
        run: docker push l7mp/stunnerd:latest
  push_chart:
    name: Push charts to the web
    runs-on: ubuntu-latest
    steps:

      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:11})

      - name: Repository dispatch with passing the tagged version
        uses: peter-evans/repository-dispatch@v2.1.1
        with:
          token: ${{ secrets.WEB_PAT_TOKEN }}
          repository: l7mp/stunner-helm
          event-type: stunner-release
          client-payload: '{"tag": "${{steps.vars.outputs.tag}}", "type": "stunner"}'