name: "release-dev"

on:
  workflow_dispatch:
  push:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '**.sh'
      - '!doc/**'
      - '!examples/**'
    branches:
      - 'main'

jobs:
  push_to_registry:
    name: Push docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:11})
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag l7mp/stunnerd:dev
      - name: Push the tagged Docker image
        run: docker push l7mp/stunnerd:dev
  push_chart:
    name: Push charts to the web
    runs-on: ubuntu-latest
    steps:

      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:11})

      - name: Triggering release workflow in the stunner-helm repo
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          github_token: ${{ secrets.WEB_PAT_TOKEN }}
          owner: l7mp
          repo: stunner-helm
          client_payload: '{"tag": "dev", "type": "stunner"}'
          workflow_file_name: publish.yaml